### ISSUE TITLE
badges not displaying anymore

### ISSUE THREAD

**Issue by DreadKnight** [codetriage/codetriage#659] opened 2017-11-29 15:01 UTC
Lately the svg badges no longer display in the Github repo README's using the markdown code at least.

**Comment by schneems** [comment] 2017-11-29 15:36
Crap, thanks.

**Comment by schneems** [comment] 2017-11-29 15:57
I think the issue is that github quit serving images via redirect. I added badges as `https://codetriage.com` instead of `https://www.codetriage.com`. I redirect from codetriage.com to `www.codetriage.com` so github would get a 301. 

I've fixed the issue, but github seems to still serve a cached value from their own cdn that is bad.

**Comment by schneems** [comment] 2017-11-29 16:16
Actually looks like that’s not the issue Rails/Rails has www but is still not rendering I opened a ticket with github. Hope they respond quick.

**Comment by schneems** [comment] 2017-11-29 19:58
Fixed via https://github.com/codetriage/codetriage/commit/3693f75ca5101c1fe64a85b1b4d0ce910f614ea8 not sure why Github won't cache a 203 status, hopefully this is a bug on their part and I can go back to using it.

**Comment by DreadKnight** [comment] 2017-11-29 20:03
All good now, well done!

**Closed** 2017-11-29 20:02 UTC
