### ISSUE TITLE
Can't delete account or unsubscribe

### ISSUE THREAD

**Issue by alexbagirov** [codetriage/codetriage#346] opened 2015-06-07 19:45 UTC
When I try to do so I get an 404 error.

**Comment by alexbagirov** [comment] 2015-06-07 19:55
It worked for me in Chrome. Problems appear in Firefox.

**Comment by nysthee** [comment] 2015-06-20 16:34
I cannot reproduce this in Firefox 37.0.2 for Ubuntu.

**Comment by schneems** [comment] 2015-06-23 18:51
Closing the issue, please comment if you're still getting emails

**Closed by schneems** 2015-06-23 18:51 UTC
